server:
  port: 9080
  servlet:
    context-path: /wykd-basic
spring:
  application:
    name: service-wykd-basic
eureka:
#  instance:
#    prefer-ip-address: true
#    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    service-url: 
      defaultZone: http://localhost:8010/wykd-eureka/eureka/