server:
  port: 9050
  servlet:
    context-path: /wykd-jiazhuang
spring:
  application:
    name: service-wykd-jiazhuang
  redis:
    host: 120.78.168.84
    port: 6379
    password:
    database: 1
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
eureka:
#  instance:
#    prefer-ip-address: true
#    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    service-url: 
      defaultZone: http://localhost:8010/wykd-eureka/eureka/
