server:
  port: 9010
  servlet:
    context-path: /wykd-movie
spring:
  application:
    name: service-wykd-movie
eureka:
  client:
    service-url: 
      defaultZone: http://localhost:8010/wykd-eureka/eureka/