server:
  port: 9020
  servlet:
    context-path: /wykd-meishi
spring:
  application:
    name: service-wykd-meishi
eureka:
  client:
    service-url: 
      defaultZone: http://localhost:8010/wykd-eureka/eureka/
feign:
  hystrix:
    enabled: true     